### ISSUE TITLE
Unable to use Float64Array::get

### ISSUE THREAD

**Issue by opatry** [leaningtech/cheerp-libs#2] opened 2015-11-12 20:44 UTC
Hi,

I'm facing an issue when I want to handle an array sent by JavaScript.

JavaScript:
```js
var stroke = null;
var points = [];
// ...
if(!stroker)
  stroker = new StrokerCPP(6);

// same error if points sent as [] instead of Float64Array
stroker.stroke(new Float64Array(points));
```

C++
```cpp

class [[jsexport]] StrokerCPP
{
public:
 StrokerCPP(){}
  void stroke(client::Float64Array jsPoints)
  {
    auto length = jsPoints.get_length(); // works
    if(length > 0)
    {
       auto val = jsPoints.get(0); // fails: Uncaught RangeError: Invalid typed array length + Uncaught TypeError: eq.get is not a function
    }
  }
};
```

Are arrays properly supported when sent by JavaScript?

**Comment by alexp-sssup** [comment] 2015-11-12 21:11
What you want to achieve is fully supported. I believe the signature for stroke should be:
oid stroke(client::Float64Array& jsPoints) // or maybe client::Float64Array

**Comment by opatry** [comment] 2015-11-12 21:17
I tried with `client::Float64Array&`, `const client::Float64Array&` (doesn't even compile since `get_length` & `get` are not `const`), `client::Float64Array*` and `client::Float64Array` but none of these worked… :(

**Comment by alexp-sssup** [comment] 2015-11-12 21:18
What is the output of /opt/cheerp/bin/clang --version?

**Comment by opatry** [comment] 2015-11-12 21:19
```sh
$ /opt/cheerp/bin/clang --version
Cheerp 1.1 clang version 3.5.0  (based on LLVM 3.5.0svn)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by opatry** [comment] 2015-11-12 21:24
The `Uncaught TypeError: eq.get is not a function` error surprises me since, from what I understand, the compilation of C++ produces JavaScript directly from cheerp headers which maps C++ call to vanilla JavaScript without any glue. So if I have a `Float64Array` both on JavaScript and C++ side, the mapping should be ok. That means the compilation produces an `eq` variable which isn't a `Float64Array`, am I right? Or `TypedArray::get` shouldn't be mapped to JavaScript `get` but `[]`?

**Comment by opatry** [comment] 2015-11-12 21:33
In fact, I tried to update the generated JavaScript and replace the `xxx.get(val)` calls to `xxx[val]` and it worked! I assume this is a compilation error.

**Comment by alexp-sssup** [comment] 2015-11-12 21:50
I'm not able to reproduce the problem neither with Cheerp 1.1 nor with our current development build. Could you attach the generated JS (possibly with the -cheerp-pretty-code option for clarity)

**Comment by alexp-sssup** [comment] 2015-11-12 21:52
Also, what engine are you using the execute the generated JavaScript?

**Comment by opatry** [comment] 2015-11-12 22:09
HTML/JS/CSS
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Stroker</title>

    <script defer src="_js/Stroker.js"></script>

    <script type="text/javascript">
      var stroker = null;
      var points = [];

      var parent = null;

      var tempCanvas = null;

      function stroke(temp)
      {
        if((temp && tempCanvas))
        {
          if(!stroker)
            stroker = new StrokerCPP(6);
          
          var c = tempCanvas;
          var ctx = c.getContext("2d");

          if(temp)
          {
            ctx.clearRect(0, 0, c.width, c.height);
          }

          stroker.stroke(ctx, new Float64Array(points));
        }
        return false;
      }

      function scale(val)
      {
        return val * window.devicePixelRatio;
      }

      function configure(p, c)
      {
        // clientWidth excludes border, offsetWidth includes it
        var cssWidth = p.offsetWidth;

        c.width = scale(cssWidth);
        // FIXME define a meaningful value
        var height = 768;
        c.height = scale(height);

        p.style.height = height + "px";

        var ctx = c.getContext('2d');
        ctx.lineJoin = "round";
        ctx.lineCap = "round";
        ctx.fillStyle = "#00AFD9";
        ctx.strokeStyle = "#00AFD9";
      }

      function draw(e)
      {
        if(parent)
        {
          console.log("typeof coords " + typeof(e.pageX) + " " + e.pageX);
          points.push(scale(e.pageX - parent.offsetLeft));
          points.push(scale(e.pageY - parent.offsetTop));
          stroke(true);
        }
      }

      function endPointer(e)
      {
        if(parent)
        {
          stroke(false);
          points = [];
          tempCanvas.removeEventListener("mousemove", draw, false); 
        }
      }

      function init()
      {
        parent = document.getElementById("demo");

        tempCanvas = document.getElementById("temp"); //parent.lastChild;

        configure(parent, tempCanvas);

        tempCanvas.addEventListener("mousedown", function() {
            tempCanvas.addEventListener("mousemove", draw, false);
          } , false);
        tempCanvas.addEventListener("mouseup", endPointer, false);
      }

      window.onload = function() {
        init();
      };
    </script>

    <style type="text/css">
    .content
    {
      width: 800px;
      margin: 0 auto;
    }

    canvas
    {
      width: 100%;
    }

    .canvas-temp-rendering
    {
      box-shadow: 0 1px 2px rgba(0,0,0,.25);
      background: #F4F5F6;
    }

    </style>
  </head>
<body>
  <div class="content">
    <div id="demo" class="canvas-parent">
      <canvas id="temp" class="canvas canvas-temp-rendering"></canvas>
    </div>
  </div>
</body>
</html>
```

CPP
```cpp
#include <string>

#include <cheerp/client.h>
#include <cheerp/clientlib.h>

class [[jsexport]] StrokerCPP
{
public:
  StrokerCPP(float width)
  {
  }

  void stroke(client::CanvasRenderingContext2D* ctx, client::Float64Array& jsPoints)
  {
    auto size = jsPoints.get_length();

    client::console.log(std::to_string(size).c_str());

    if(size > 0)
      auto val = jsPoints.get(0);
  }
};

void webMain() [[client]]
{
}
```

Generated JS (`-cheerp-pretty-code`)
```js
"use strict"
function StrokerCPP(a0){
	this.i0=0;
	this.d=[this];
	__ZN10StrokerCPPC1Ef(this,a0);
}
StrokerCPP.prototype.stroke=function (a0,a1){
	return __ZN10StrokerCPP6strokeEPN6client24CanvasRenderingContext2DERNS0_12Float64ArrayE(this,a0,a1);
}
var aSlot=null;var nullArray=[null];var nullObj={d:nullArray,o:0};
function __Z7webMainv(){
	return ;
}
function __ZN10StrokerCPPC1Ef(Lthis,Lwidth){
	return ;
}
function __ZN10StrokerCPP6strokeEPN6client24CanvasRenderingContext2DERNS0_12Float64ArrayE(Lthis,Lctx,LjsPoints){
	var label=0;
	var tmp3=aSlot={i0:0,i1:0,a2:nullArray};
	var tmp4=LjsPoints.length;
	__ZSt9to_stringd(tmp3,tmp4);
	var tmp5=(tmp3.a2);
	var LretConstructor$pi$pi=String();
	var tmp1=(tmp5[0>>0]&255);
	L10:do{
		if(((tmp1&255)===(0&255))){
		}else{
			var Lgeptoindexphi=0;
			while(1){
				var tmp6=String.fromCharCode(((tmp1<<24)>>24)>>0);
				var LretConstructor$pi$pi=LretConstructor$pi$pi.concat(tmp6);
				var Lgeptoindexphi=((Lgeptoindexphi>>0)+(1>>0)>>0);
				var tmp1=(tmp5[(0>>0)+(Lgeptoindexphi>>0)>>0]&255);
				if(((tmp1&255)===(0&255))){
					break L10;
				}else{
				}
			}
		}
	}while(0);
	var LretConstructor$pi$pi=String(LretConstructor$pi$pi);
	console.log(LretConstructor$pi$pi);
	if(!((tmp5.length===1 && tmp5===nullArray && 0===0))){
	}
	if(!((tmp4>0))){
		return ;
	}
	LjsPoints.get(0); // HERE is the issue, if replaced by LjsPoints[0], works perfectly
	return ;
}
```

I only pasted the beginning of the file, if you think I missed some stuff, please tell me.

**Comment by alexp-sssup** [comment] 2015-11-12 22:29
Thanks a lot for reporting this bug, this is very interesting. Turns out that Chrome and Firefox does not provide the .get function, but node.js does and the standard clearly state that such function exists. Currently cheerp does not support the [ ] operator on typed arrays, but you can work around the problem using the following construct:

double* buffer = __builtin_cheerp_make_regular<double>(&jsPoints, 0);

You can now access buffer as a standard array, please note that the operation does not do any copy so the new array is an alias for the existing one.

As a side note, you can pass integers and doubles directly to console log without passing through std::string.

**Comment by opatry** [comment] 2015-11-12 22:46
I had to use `double* buffer = __builtin_cheerp_make_regular<double>(&jsPoints, 0);` instead of `double* buffer = __builtin_cheerp_make_regular(&jsPoints, 0);` to make it compile.

Then, as you told, it worked.

Regarding your comment on `client::console.log`, I can't use it directly as told:

```cpp
double v = 10;
client::console.log(d);
```

```
: error: conversion
      from 'double' to 'const client::String' is ambiguous
    client::console.log(v);
```

**Comment by opatry** [comment] 2015-11-12 22:53
> Currently cheerp does not support the [ ] operator on typed arrays

What do you mean? `operator[]` from C++ code?
Why not mapping `TypedArray::get()` on JavaScript `[]`? Maybe the two functions are not the same?

I'm curious, what is the difficulty with `operator[]` on `TypedArray`? I naïvely thought that it would be a simple mapping but if you didn't do it, I assume this is not that easy.

**Comment by alexp-sssup** [comment] 2015-11-12 22:56
conversion from double to client::String will be supported is indeed not supported in 1.1 but will be in 1.2

The reason that TypedArray::get is not mapped to [ ] is that there is no special logic for any browser APIs, they are directly converted to the corresponding JS call.

Operator [ ] is support for already supported for Array, but not yet for TypedArrays, we will fix this for 1.2

**Comment by opatry** [comment] 2015-11-12 23:07
> The reason why TypedArray::get is not mapped to [ ] is that there is no special logic for any browser APIs, they are directly converted to the corresponding JS call.

Makes sense.

Do you have a public roadmap of cheerp?
How can I use the current work in progress version of cheerp?

Sorry if it's explained somewhere, I didn't find it on the wiki nor the website.
In fact, it wasn't neither very obvious to determine how to submit an issue. Maybe you could add some words on that on the website?

**Comment by alexp-sssup** [comment] 2015-11-13 10:15
We don't have a public roadmap at this time and we try to prioritize the work based on the feedback from our users. You can build Cheerp from source by following the instructions in the README.md file which is available in every sub project here on github. The build instructions on the Wiki are targeted for release 1.1 and will be updated when 1.2 is released.

We do bug tracking on Launchpad at the moment https://bugs.launchpad.net/cheerp/. This is documented on our site but probably in a not very accessible place. We will rework that to increase clarity.

**Comment by opatry** [comment] 2015-11-13 10:58
Regarding the build instruction, it is explained in the wiki, I missed it, sorry!
Ok for bug reporting, still as you mentioned I didn't found the page where the bug report workflow is described! But now I have the information ;)

**Comment by alexp-sssup** [comment] 2015-12-02 11:38
I'm migrating issue tracking for Cheerp into the cheerp-meta project: https://github.com/leaningtech/cheerp-meta/issues/1

**Closed** 2015-12-02 11:38 UTC
